// ====== Currency ======
export const CURRENCY_CHANGE_AMOUNT = 'CHANGE_CURRENCY_AMOUNT';
export const CURRENCY_SWAP_CURRENCY = 'SWAP_CURRENCY';
export const CURRENCY_CHANGE_BASE = 'CHANGE_BASE_CURRENCY';
export const CURRENCY_CHANGE_QUOTE = 'CHANGE_QUOTE_CURRENCY';
export const CURRENCY_GET_INITIAL_CONVERSION = 'GET_INITIAL_CONVERSION';
// Currency Error
export const CURRENCY_CONVERSION_RESULT = 'CONVERSION_RESULT';
export const CURRENCY_CONVERSION_ERROR = 'CONVERSION_ERROR';

// ====== Theme ======
export const THEME_CHANGE_PRIMARY_COLOR = 'CHANGE_PRIMARY_COLOR';
